ThingCache tests
kontur-csharper/mocks pull request #5
Opened 2020-04-09 13:33 UTC by quietBlow

2020-04-09 13:44 UTC, zharkovstas requested changes

2020-04-09 13:44 UTC, zharkovstas commented on ThingCache/ThingCacheTests.cs
> +            A.CallTo(() => thingService.TryRead(thingId1, out t)).Returns(true).AssignsOutAndRefParameters(thing1);
Можно просто `out thing1` указать вместо `AssignsOutAndRefParameters`

2020-04-09 13:44 UTC, zharkovstas commented on ThingCache/ThingCacheTests.cs
> +            A.CallTo(() => thingService.TryRead(thingId1, out t)).MustHaveHappened(Repeated.Exactly.Once);
Желательно проверить, что не просто в сервис ходим один раз, но так же что при этом Get действительно возвращает закэшированный результат

2020-04-09 13:44 UTC, zharkovstas commented on ThingCache/ThingCacheTests.cs
> +            Assert.That(t, Is.Null);
Неплохо бы протестить, как кэш в этом случае работает: закэширует ли он null

2020-04-09 13:44 UTC, zharkovstas commented on ThingCache/ThingCacheTests.cs
> +    public class ThingCacheTests
Еще бы докинуть тестов на доставание предметов по нескольким ключам, чтобы убедиться, что кэш умеет кэшировать несколько предметов

2020-04-09 14:15 UTC, quietBlow commented on ThingCache/ThingCacheTests.cs
> +    public class ThingCacheTests
А есть же тест Get_ReturnsThingByThingId с TestCaseSource(nameof(ValidIdentifiers))

2020-09-07 07:03 UTC, closed without merging

2020-09-07 07:03 UTC, disturm commented
Похоже PR устарел